# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_population_main_window(object):
    def setupUi(self, population_main_window):
        population_main_window.setObjectName("population_main_window")
        population_main_window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(population_main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.initial_population_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.initial_population_line_edit.setText("")
        self.initial_population_line_edit.setObjectName("initial_population_line_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.initial_population_line_edit)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.max_population_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.max_population_line_edit.setText("")
        self.max_population_line_edit.setObjectName("max_population_line_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.max_population_line_edit)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.growth_rate_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.growth_rate_line_edit.setText("")
        self.growth_rate_line_edit.setObjectName("growth_rate_line_edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.growth_rate_line_edit)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.steps_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.steps_line_edit.setText("")
        self.steps_line_edit.setObjectName("steps_line_edit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.steps_line_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setObjectName("reset_button")
        self.verticalLayout.addWidget(self.reset_button)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.plot_area_layout = QtWidgets.QHBoxLayout()
        self.plot_area_layout.setObjectName("plot_area_layout")
        self.horizontalLayout.addLayout(self.plot_area_layout)
        self.horizontalLayout.setStretch(1, 5)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        population_main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(population_main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        population_main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(population_main_window)
        self.statusbar.setObjectName("statusbar")
        population_main_window.setStatusBar(self.statusbar)

        self.retranslateUi(population_main_window)
        QtCore.QMetaObject.connectSlotsByName(population_main_window)

    def retranslateUi(self, population_main_window):
        _translate = QtCore.QCoreApplication.translate
        population_main_window.setWindowTitle(_translate("population_main_window", "MainWindow"))
        self.label.setText(_translate("population_main_window", "Initial Population"))
        self.label_2.setText(_translate("population_main_window", "Max Population"))
        self.label_3.setText(_translate("population_main_window", "Growth Rate"))
        self.label_4.setText(_translate("population_main_window", "Number of Steps"))
        self.reset_button.setText(_translate("population_main_window", "Reset"))
